[build]
target = "wasm32-unknown-unknown"
# rustflags = ["--cap-lints=allow"]

[target.wasm32-unknown-unknown]
# This helps the linker find the correct tools in the WSL environment
linker = "rust-lld"